// Editorial spread content — 6 articles
const SLIDES = [
  {
    no: '01',
    kicker: 'DISPATCH / TOKYO',
    title: 'The Quiet Architecture of the Konbini',
    standfirst: 'How a 24-hour grid of fluorescent boxes became the warmest room in the city.',
    body: 'In the lull between the last train and the first, the konbini is not a shop. It is a heated rectangle. A taxonomy of onigiri. A small, lit promise that the night has not yet ended.',
    author: 'M. Hayashi',
    issue: 'No. 014',
    date: '04 / 26',
    pages: '12—21',
    tag: 'urbanism',
    hue: '#fef200',
    swatch: 'A',
  },
  {
    no: '02',
    kicker: 'PROFILE / OSAKA',
    title: 'Forty-Two Years of the Same Bowl of Udon',
    standfirst: 'Tetsuo Murakami has not changed the recipe. The neighbourhood, however, has.',
    body: 'There is a bowl. There is a man. There is a queue that bends around the corner of a street that used to be a canal. In Murakami-san’s shop, the broth is the constant; everything else is weather.',
    author: 'A. Toda',
    issue: 'No. 014',
    date: '04 / 26',
    pages: '22—31',
    tag: 'profile',
    hue: '#ff4d2e',
    swatch: 'B',
  },
  {
    no: '03',
    kicker: 'ESSAY / DIGITAL',
    title: 'Against the Infinite Scroll',
    standfirst: 'A short manifesto for endings, edges, and the dignity of the last page.',
    body: 'Somewhere along the way the bottom of the page became a moral failure. We have built feeds without floors. This is not generosity; it is a refusal to let the reader leave.',
    author: 'K. Beaumont',
    issue: 'No. 014',
    date: '04 / 26',
    pages: '32—37',
    tag: 'essay',
    hue: '#0a0a0a',
    swatch: 'C',
  },
  {
    no: '04',
    kicker: 'OBJECT / BERLIN',
    title: 'A Brief History of the Index Card',
    standfirst: 'Before the database, before the spreadsheet — there was a 3×5 rectangle.',
    body: 'Linnaeus did it with slips of paper. Luhmann did it with a wooden cabinet. The index card is the original hyperlink: a physical object that points elsewhere, and waits.',
    author: 'R. Kessler',
    issue: 'No. 014',
    date: '04 / 26',
    pages: '38—45',
    tag: 'object',
    hue: '#1a4dff',
    swatch: 'D',
  },
  {
    no: '05',
    kicker: 'FIELD / KYOTO',
    title: 'The Gardener Who Refuses to Plan',
    standfirst: 'Forty seasons in, Yoko Saito still walks the moss every morning before deciding.',
    body: 'A plan, she says, is a kind of disrespect. It assumes the garden will be the same tomorrow as it was when you drew it. The garden is never the same. It is barely the same by lunch.',
    author: 'S. Imura',
    issue: 'No. 014',
    date: '04 / 26',
    pages: '46—55',
    tag: 'field',
    hue: '#c8e870',
    swatch: 'E',
  },
  {
    no: '06',
    kicker: 'COLOPHON',
    title: 'On the Making of This Issue',
    standfirst: 'Set in Fraunces and Space Mono. Printed on no paper at all.',
    body: 'This issue was assembled in five cities and one terminal window. Errors are ours; the spaces between the columns belong to the reader.',
    author: 'The Editors',
    issue: 'No. 014',
    date: '04 / 26',
    pages: '56—58',
    tag: 'colophon',
    hue: '#e8e6e0',
    swatch: 'F',
  },
];

window.SLIDES = SLIDES;
